version: '3.8'

services:
  postgres:
    image: postgres:15 
    container_name: sj-postgres-container
    environment:
      POSTGRES_DB: sjdatabase
      POSTGRES_USER: sjuser
      POSTGRES_PASSWORD: sjpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
